ci: build fix

diff --git a/cider-ci/uberjar_task-component.yml b/cider-ci/uberjar_task-component.yml
--- a/cider-ci/uberjar_task-component.yml
+++ b/cider-ci/uberjar_task-component.yml
@@ -35,6 +35,6 @@ scripts:
       if [ ! -z ${S3_CI_ENDPOINT:+x} ] ; then
         if [ ! "$(aws --quiet --only-show-errors --no-progress --endpoint $S3_CI_ENDPOINT s3 cp s3://${S3_CI_CACHE_BUCKET}/${S3_UBERJAR_FILE_NAME} ${UBERJAR_PATH})" ]; then
           echo "INFO: No S3 cached uberjar found; uploading ours now"
-          aws --endpoint $S3_CI_ENDPOINT s3 cp ${UBERJAR_PATH} s3://${S3_CI_CACHE_BUCKET}/${S3_UBERJAR_FILE_NAME}
+          aws --endpoint $S3_CI_ENDPOINT s3 cp ${UBERJAR_PATH} s3://${S3_CI_CACHE_BUCKET}/${S3_UBERJAR_FILE_NAME} || echo "S3 upload failed, ignoring error!"
         fi
       fi
